- name: setup prompt
  ansible.builtin.shell: set-prompt gethub-runner

- name: add github runner user
  ansible.builtin.user:
    name: grunner 

- name: github dir
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: grunner
    group: ec2-user
  
- name: Download & Extract Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: /actions-runner
    remote_src: yes
    owner: grunner
    group: ec2-user

- name: Download Github CLI
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repos.d/gh-cli.repo

- name: install github cli
  ansible.builtin.dnf:
    name: gh
    state: latest

# - name: Grab Token
#   ansible.builtin.shell: |
#    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/AkshayreddyDevops/actions/runners/registration-token|jq .token
#   register: out
#   become_user: "gaddam-akshay"

# - name: Print Token
#   ansible.builtin.debug:
#     msg: "{{ out }}" 
 
- name: install libicu dependence 
  ansible.builtin.dnf:
    name: libicu
    state: latest

# - name: config github Runner
#   become_user: "grunner"
#   ansible.builtin.shell: |
#     ./config.sh --url https://github.com/AkshayreddyDevops --token BJR6Q2NOR5O66ITTNUQX2HTGTYYNS --runnergroup Default --name ec2 --labels rhel --work _work --replace  
#   args: 
#     chdir: /actions-runner
  
# - name: config github Runner
#   become_user: "grunner"
#   ansible.builtin.shell: |
#     ./svc.sh install grunner; ./svc.sh start
#   args:
#     chdir: /actions-runner

- name: Download terraform
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    path: /etc/yum.repos.d/hashicorp.repo

- name: Install Terraform
  ansible.builtin.dnf:
    name: terraform
    state: latest

