- name: setup prompt
  ansible.builtin.shell: set-prompt gethub-runner

- name: github dir
  ansible.builtin.file:
    path: /actions-runner
    state: directory

- name: Download & Extract Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: /actions-runner
    remote_src: yes

- name: Download Github CLI
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repos.d/gh-cli.repo

- name: install github cli
  ansible.builtin.dnf:
    name: gh
    state: latest

- name: Grab Token
  ansible.builtin.shell: |
   gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/AkshayreddyDevops/actions/runners/registration-token|jq .token
  register: out

- name: Print Token
  ansible.builtin.debug:
    msg: "{{ out }}"    

