- name: setup prompt
  ansible.builtin.shell: set-prompt gethub-runner

- name: github dir
  ansible.builtin.file:
    path: /actions-runner
    state: directory

- name: Download & Extract Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: /actions-runner
    remote_src: yes

- name: Download Github CLI
  ansible.builtin.git_url:
    src: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repo.d/gh-cli.repo

- name: install grthub cli
  ansible.builtin.dnf:
    - name: gh-cli
      state: latest
